// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=goa-getting_started_guide/design
// --out=$(GOPATH)/src/goa-getting_started_guide
// --version=v1.3.1

package client
